apiVersion: apps/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  rules:
  - host: 192.168.49.2.nip.io
    http:
      paths:
      - backend:
          serviceName: deploy-image-57474b9b79-dbf7z
          servicePort: 80
        path: /